### ISSUE TITLE
Putting a space to sleep is not guaranteed and no feed-back about it

### ISSUE THREAD

**Issue by nicolasbelanger** [loft-sh/loft#65]
**Context**
Actively monitoring a vCluster using [k9s](https://github.com/derailed/k9s).

**Issue**
When trying to put the space in which the vCluster lives to sleep, it is silently accepted (`State saved in cluster loft-cluster`, or exit 0 on the CLI), but woken-up right after (hit refresh on browser, space status is `Active`, same with `loft list spaces`).

**Expected**
The space to be in status `Sleeping`, or at least a feedback in the UI/CLI.

Thanks! 

**_Edit_**
Worth saying that sleeping does work as expected if not using k9s...

**Comment by FabianKramm** [comment]
@nicolasbelanger thanks for reporting this issue! I guess the problem here is that k9s is waking up the space exactly after putting it to sleep. You could circumvent the problem by ignoring certain actions as activity in the space, for how to configure take a look at the [sleepmode docs](https://loft.sh/docs/self-service/sleep-mode#how-is-the-inactivity-determined).

**Comment by FabianKramm** [comment]
@nicolasbelanger I'll close this issue for now, if this issue comes up again or the provided solution does not work, feel free to reopen it
